package application;

public class Review {

    private int id;
    private String targetId;
    private String targetType;
    private String text;
    private String author;

    // Constructor for creating a new review (ID generated by DB)
    public Review(String targetId, String targetType, String text, String author) {
        if (text == null || text.trim().isEmpty()) {
            throw new IllegalArgumentException("Review text cannot be empty");
        }
        if (!"QUESTION".equals(targetType) && !"ANSWER".equals(targetType)) {
            throw new IllegalArgumentException("Target type must be QUESTION or ANSWER");
        }
        this.targetId = targetId;
        this.targetType = targetType;
        this.text = text;
        this.author = author;
    }

    // Constructor for fetching from DB
    public Review(int id, String targetId, String targetType, String text, String author) {
        this(targetId, targetType, text, author);
        this.id = id;
    }

    // Getters
    public int getId() {
        return id;
    }

    public String getTargetId() {
        return targetId;
    }

    public String getTargetType() {
        return targetType;
    }

    public String getText() {
        return text;
    }

    public String getAuthor() {
        return author;
    }

    @Override
    public String toString() {
        return "Review: " + text + " (By: " + author + ")";
    }
}
